name: Create PR

on:
  # Only run when manually triggered
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      # outdated action
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
  
      - name: Make change
        run: touch test.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Test commit
          title: Test PR
          draft: always-true
