on:
  push:
    branches:
      - dependabot/**

permissions:
  contents: write

jobs:
  create-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: |
          git config --global user.name "Test"
          git config --global user.email test@example.invalid
          touch test.txt
          git add .
          git commit -m "test"
          git push
      # outdated action
      - uses: actions/checkout@v4.2.1
