on: push

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4.1.0
        with:
          script: |
            /*github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })*/
            throw new Error("my error")
