on: push

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4.1.0
        with:
          script: |
            console.log(context.serverUrl)
            console.log(process.env.GITHUB_SERVER_URL)
